server:
  port: 8763

spring:
  application:
    name: http-user-service
  profiles:
      #引入配置
      include: base

eureka:
  client:
    #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址，多个地址可用，用","分割
    #service-url:
      #defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
